name: Deals Agent
on:
  schedule:
    - cron: "0 7 * * *"   # 07:00 UTC = 09:00 Europe/Warsaw
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps
          python -m playwright --version

      - name: Show workspace
        run: |
          set -euxo pipefail
          pwd
          ls -la
          echo "Python:"
          python -V
          which python
          echo "Pip list (top):"
          pip list | head -n 50

      - name: Telegram ping (test)
        if: ${{ secrets.TELEGRAM_BOT_TOKEN != '' && secrets.TELEGRAM_CHAT_ID != '' }}
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -euxo pipefail
          curl -s "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="✅ GitHub Actions: бот жив."

      - name: Playwright smoke test
        run: |
          set -euxo pipefail
          python - <<'PY'
          from playwright.sync_api import sync_playwright
          with sync_playwright() as p:
              b = p.chromium.launch(headless=True, args=["--no-sandbox"])
              page = b.new_page()
              page.goto("https://example.com", timeout=30000)
              print("Title:", page.title())
              b.close()
          PY

      - name: Run agent
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -euxo pipefail
          test -f scraper.py && echo "scraper.py found" || (echo "scraper.py NOT found" && exit 1)
          python scraper.py
